Project setup
Globalika/Countries pull request #1
Opened 2021-11-24 12:46 UTC by Globalika

added 3rd party libraries with cocoapods
added swiftlint file
made read me instruction
set up git ignore 
integrate apollo client with api https://countries.trevorblades.com/

2021-11-24 12:57 UTC, apolwork requested changes

2021-11-24 12:57 UTC, apolwork commented on Countries/Countries/AppDelegate.swift
> +    }
Do you plan to use CoreData in your application?

2021-11-24 12:57 UTC, apolwork commented on Countries/Countries/Queries.graphql
> +}
Do you have plans to replace this query with more appropriate?

2021-11-24 12:57 UTC, apolwork commented on Countries/Countries/ViewController.swift
> +
Spacing

2021-11-24 12:57 UTC, apolwork commented on Countries/Podfile
> +# platform :ios, '9.0'
Do we need this comment? Or it should be removed?

2021-11-24 12:57 UTC, apolwork commented on Countries/Podfile
> +  # Comment the next line if you don't want to use dynamic frameworks
saa

2021-11-24 12:57 UTC, apolwork commented on README.md
> +###### - paste in console following line
It is not necessary to mark list items as headers. Do you made this intentionally?

2021-11-24 12:57 UTC, apolwork commented on README.md
> +###### - open Countries.xcworkspace to launch application
saa

2021-11-25 09:38 UTC, Globalika commented on Countries/Countries/AppDelegate.swift
> +    }
No. I will delete it in next PR

2021-11-25 09:38 UTC, Globalika commented on Countries/Countries/Queries.graphql
> +}
Yes. I will add new query in next PR

2021-11-25 09:43 UTC, Globalika commented
fixed by apolwork comments*

2021-11-25 09:58 UTC, ambrusha commented on Countries/.swiftlint.yml
> +excluded:
Add Countries/Countries/API.swift and Countries/R.generated.swift to excluded

2021-11-25 09:58 UTC, ambrusha commented on Countries/Countries/AppDelegate.swift
> +
one line not three...

2021-11-25 09:58 UTC, ambrusha commented on Countries/Countries/AppDelegate.swift
> +
And why `// MARK: - Core Data` still here?

2021-11-25 09:58 UTC, ambrusha commented on Countries/Countries/Countries.xcdatamodeld/.xccurrentversion
> +</plist>
this file looks like for CoreData

2021-11-25 09:58 UTC, ambrusha commented on Countries/Countries/Countries.xcdatamodeld/Countries.xcdatamodel/contents
> +</model>
this file looks like for CoreData

2021-11-25 09:58 UTC, ambrusha commented on README.md
> +- paste in console following line
```suggestion
- run from console `pod install`
```

2021-11-25 10:20 UTC, ambrusha commented on Countries/Countries/AppDelegate.swift
> +import CoreData
remove `import CoreData` please?

2021-11-25 10:29 UTC, ambrusha approved these changes

2021-11-25 10:29 UTC, merged