Table cell design
Globalika/Countries pull request #12
Opened 2021-12-02 10:11 UTC by Globalika

designed views architecture
added gradient
rearranged functions

2021-12-02 10:52 UTC, khrystyna-sb reviewed
interesting decision to move constraints to extension..

2021-12-02 10:52 UTC, khrystyna-sb commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +    }
do you really need to put gradient to layoutSubviews()?

2021-12-02 11:03 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +    }
from documentation: https://developer.apple.com/documentation/uikit/uiview/1622482-layoutsubviews

'You should override this method only if the autoresizing and constraint-based behaviors of the subviews do not offer the behavior you want. You can use your implementation to set the frame rectangles of your subviews directly.'
anfd thats was the only way for gradient to work properly :)

2021-12-02 11:09 UTC, khrystyna-sb approved these changes
interesting decision to put constraints to extension

2021-12-02 11:36 UTC, apolwork requested changes

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +            UIColor(rgb: Constants.cellGradientSecondColor).cgColor
You could store CGColor as constants

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +    }
You should not use extension to override existing functionality. It is contradict the idea of extension in Swift

https://docs.swift.org/swift-book/LanguageGuide/Extensions.html

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +        stack.spacing = 20
minor: use constants for all literals, please

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +        stack.spacing = 20
minor: use constants for all literals, please

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +            indentView.heightAnchor.constraint(equalToConstant: 160)
minor: use constants for all literals, please

Take a look on `UIEdgeInset`. It could help you work with padding more efficiently

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +        indentView.layer.insertSublayer(gradient, at: 0)
`indentView.layer.insertSublayer(gradient, at: 0)` this code is not related to func name. 
Please move to a correct place.

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +        // TODO configure horizontal stack view
What do you plan to configure in this function?

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
>              countryNameLabel.rightAnchor.constraint(equalTo: self.rightAnchor),
Do you use this func?

2021-12-02 11:36 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +    }
Do you use this func?

2021-12-02 11:59 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +        // TODO configure horizontal stack view
i`m planning to configure objects in horizontalstack (flag image and labels)

2021-12-02 11:59 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
>              countryNameLabel.rightAnchor.constraint(equalTo: self.rightAnchor),
i will use it after horizontal stack configuraton

2021-12-02 12:00 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/CountryViewCell.swift
> +    }
same here after  horizontal stack configuraton

2021-12-03 09:39 UTC, apolwork approved these changes

2021-12-03 09:41 UTC, merged