Cell decorator view
Globalika/Countries pull request #16
Opened 2021-12-03 16:47 UTC by Globalika

added cell decorator view with shadow gradient and corner radius
![Screenshot 2021-12-03 at 18 46 54](https://user-images.githubusercontent.com/66167568/144640434-60f07ded-bfb7-4b31-a89d-130b96c0b076.png)

2021-12-07 06:32 UTC, khrystyna-sb approved these changes

2021-12-07 11:55 UTC, apolwork requested changes

2021-12-07 12:59 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/CellDecoratorView.swift
> +                                  Constants.secondColorGradientStopLocation]
wrong implementation agree. will change it to just have two colors

2021-12-07 13:06 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/CellDecoratorView.swift
> +    }
after investigation your question i make conclusion that i don`t need to do this

2021-12-09 09:48 UTC, apolwork approved these changes

2021-12-09 09:49 UTC, merged