Multiplerequests
Globalika/Countries pull request #22
Opened 2021-12-14 10:02 UTC by khrystyna-sb

Divided the request into two parts, the existing data goes to the next screen, where the rest is loaded.

2021-12-14 11:09 UTC, Globalika requested changes

2021-12-14 11:09 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountryDetailsController.swift
> +//        configureRefreshControl()
comment line

2021-12-14 11:14 UTC, Globalika approved these changes

2021-12-14 11:33 UTC, apolwork requested changes

2021-12-14 11:33 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/Queries.graphql
> +
I would suggest to split into separate query files

2021-12-14 11:33 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountryDetailsController.swift
>                                  "\(country.currency ?? Constants.notApplicableField)"))
This piece of should not be executed while your data is loading. Could you double check?
Second point. You should use loaded data for all information on your screen when it is possible

2021-12-14 11:33 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountryDetailsController.swift
> +
Extra spaces

2021-12-14 11:33 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountriesController.swift
> +        detailsController.countryCode = countries[indexPath.row].code
Why do you pass countryCode, when you have it in your basic object?

2021-12-14 16:04 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountryDetailsController.swift
> +            self.countryInfo.append(("Calling Code:", "\(country.phone)"))
Why do use use `self.countryInfo` instead of plain `countryInfo`

2021-12-14 16:04 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountryDetailsController.swift
> +}
Personally, I don't like the idea of using extension in this way. But I am ok with that for now

2021-12-14 16:04 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountryDetailsController.swift
> +    func fillDetailsViewWithNewData() {
Please, do not use "new" in names. "new" is suitable only in cases when you create new objects.

2021-12-15 11:21 UTC, apolwork commented on CountriesOfTheWorld/CountriesOfTheWorld/Extensions/UIStackViewExtensions.swift
> +    }
```suggestion
    func removeAllSubviews() {
        self.subviews.forEach { $0.removeFromSuperview }
    }
```

UIStackView has difference between arranged subview and subviews, so naming is not 100% correct. Also you could simplify your code.
JFYI.

2021-12-15 11:41 UTC, khrystyna-sb commented on CountriesOfTheWorld/CountriesOfTheWorld/Extensions/UIStackViewExtensions.swift
> +    }
wow, thank you!

2021-12-15 12:13 UTC, merged