Search countries
Globalika/Countries pull request #24
Opened 2021-12-15 17:10 UTC by khrystyna-sb

![Screenshot 2021-12-15 at 19 10 02](https://user-images.githubusercontent.com/82377917/146232503-580b6d0d-70c2-4707-8706-9916079752e5.png)
![Screenshot 2021-12-15 at 19 09 45](https://user-images.githubusercontent.com/82377917/146232518-fe3bdd7f-ecb5-4740-ab5c-c65634f10d13.png)

2021-12-16 09:02 UTC, Globalika requested changes

2021-12-16 09:02 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountriesController.swift
> +            (country.capital ?? "N/A").lowercased().contains(searchText.lowercased()) ||
you can use constant at  247 line static let notApplicableField = "N-A"

2021-12-16 09:02 UTC, Globalika commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountriesController.swift
> +        tableView.reloadData()
if filteredCountries = nil there will be no data on screen. do you want this behaviour?

2021-12-16 10:46 UTC, khrystyna-sb commented on CountriesOfTheWorld/CountriesOfTheWorld/ViewControllers/CountriesController.swift
> +        tableView.reloadData()
if filteredCountries = nil there will be all countries on screen.
 cell.updateCell(country: filteredCountries?[indexPath.row] ?? countries[indexPath.row])

2021-12-16 12:26 UTC, Globalika approved these changes

2021-12-17 09:44 UTC, ambrusha approved these changes

2021-12-17 11:43 UTC, merged